Repository heroku/heroku-buildpack-java, pull requests merged in 2020-10, with the labels that each got.

#151 v67
  CHANGELOG.md
Labels: languages-review

#153 Enable heroku-20 testing
  .circleci/config.yml
  CHANGELOG.md
  test/spec/java_spec.rb
Labels: languages-review

#154 Update skip changelog action
  .github/dependabot.yml
  .github/workflows/check_changelog.yml
Labels: languages-review, skip changelog

#155 Cleanup integration tests
  Gemfile
  Gemfile.lock
  hatchet.lock
  test/spec/agent_spec.rb
  test/spec/db_spec.rb
  test/spec/java_spec.rb
  test/spec/maven_spec.rb
  test/spec/spec_helper.rb
  test/spec/spring_spec.rb
Labels: languages-review, skip changelog

#156 add test for getting started guide from jvm commons
  hatchet.json
  hatchet.lock
  test/spec/getting_started_spec.rb
Labels: skip changelog
